apiVersion: v1
kind: Service
metadata:
  name: {{ include "timeservice.fullname" . }}
  labels:
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    {{- include "timeservice.selectorLabels" . | nindent 4 }}