
replicaCount: 1

image:
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.12.0
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  # Give role created by OIDC in terraform, available in tf outputs
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::774305577388:role/test-cloud-controller
  name: aws-load-balancer-controller
  automountServiceAccountToken: true
  imagePullSecrets:

# These values need to be added for first setup, found in terraform output
# or the AWS console unser EKS and VPC
clusterName: default_cluster
vpcId: "vpc-02ad34a8204664731"

# Enabling this creates resources that will not be managed by TF and
# stay even after uninstalling release. This can error out your tf destroy
# Set to true if using your own k8s cluster with permanent VPC
enableBackendSecurityGroup: false