
replicaCount: 1

image:
  repository: public.ecr.aws/eks/aws-load-balancer-controller
  tag: v2.12.0
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  # Give role created by OIDC in terraform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::774305577388:role/dev-cloud-controller
  name: aws-load-balancer-controller
  automountServiceAccountToken: true
  imagePullSecrets:

clusterName: default_cluster
vpcId: "vpc-0e6835c4d7ad26ad4"

# Enabling this creates resources that will not be managed by TF and
# stay even after uninstalling release. This can error out your tf destroy
# Set to true if using your own k8s cluster with permanent VPC
enableBackendSecurityGroup: false
  
# enableCertManager: true