name: Deployment

on:
  push:
    branches: main

jobs:

  DetectChanges:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      terraform: ${{ steps.filter.outputs.terraform }}
      deploy_system: ${{ steps.filter.outputs.deploy_system }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Filtering changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          terraform:
            - 'terraform/**'
          deployment:
            - 'helmfile.d/**'

  InfraBuild:
    name: Building IaC changes to infrastructure
    needs: DetectChanges
    if: ${{ needs.DetectChanges.outputs.terraform == 'true' }}
    defaults:
      run:
        working-directory: ./terraform
    runs-on: ubuntu-latest
    env: 
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./terraform/
          backend_config_file: ./terraform/default.s3.tfbackend
          label: k8s_dev

      - name: Calculate build version
        id: tf_semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          bump_each_commit: true
          bump_each_commit_patch_pattern: "(PATCH-TF)"
          version_format: "${major}.${minor}.${patch}"
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          enable_prerelease_mode: true
          change_path: "terraform/"

      - name: Get PR number of push
        uses: actions/github-script@v6
        id: pr_number
        with:
          script: |
            return (   
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
          result-encoding: string
        
      - name: Comment versioning info
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          message: |
            Merged Infrastructure version: ${{ steps.tf_semver.outputs.version }}

            Infrastructure deployed :rocket:
          pr-number: ${{ steps.pr_number.outputs.result }}

  DeploymentChanges:
    needs: DetectChanges
    if: ${{ needs.DetectChanges.outputs.deployment == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      system: ${{ steps.filter.outputs.system }}
      app: ${{ steps.filter.outputs.app }}
    steps:
    - name: Filtering changes
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          system:
            - 'helmfile.d/system.yaml'
          app:
            - 'helmfile.d/app.yaml'

  UpdateDependencies:
    needs: DeploymentChanges
    if: ${{ needs.DeploymentChanges.outputs.system == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup kube    
        uses: azure/setup-kubectl@v4
        with:
          version: '1.31.4'

      - name: Set kube context
        run: aws eks --region ${{ vars.AWS_REGION }}  update-kubeconfig --name ${{ vars.CLUSTER_NAME }}

      - name: Apply CRDs
        run: kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"


  SystemDiff:
    needs: [DeploymentChanges, UpdateDependencies]
    if: ${{ needs.DeploymentChanges.outputs.system == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set kube context
        run: aws eks --region ${{ vars.AWS_REGION }}  update-kubeconfig --name ${{ vars.CLUSTER_NAME }}
      
      - name: System deployment
        uses: helmfile/helmfile-action@v2.0.4
        id: helm_diff
        with:
          helmfile-version: 'v0.170.0'
          helm-version: 'v3.17.2'
          helm-plugins: >
            https://github.com/databus23/helm-diff
          helmfile-args: -l component=system apply
      - name: Get PR number of push
        uses: actions/github-script@v6
        id: pr_number
        with:
          script: |
            return (   
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
          result-encoding: string

      - name: Comment Diff STD-OUT
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          message: |
            Ran helmfile diff for system releases

            <details>
            <summary>Diff output</summary>
            ${{ steps.helm_diff.outputs.helmfile-stdout }}            
            </details>
          pr-number: ${{ steps.pr_number.outputs.result }}

  AppDiff:
    needs: DeploymentChanges
    if: ${{ needs.DeploymentChanges.outputs.app == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Set kube context
        run: aws eks --region ${{ vars.AWS_REGION }}  update-kubeconfig --name ${{ vars.CLUSTER_NAME }}
      
      - name: App deployment
        uses: helmfile/helmfile-action@v2.0.4
        id: helm_diff
        with:
          helmfile-version: 'v0.170.0'
          helm-version: 'v3.17.2'
          helm-plugins: >
            https://github.com/databus23/helm-diff
          helmfile-args: -l component=app apply

      - name: Get PR number of push
        uses: actions/github-script@v6
        id: pr_number
        with:
          script: |
            return (   
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
          result-encoding: string

      - name: Comment Diff STD-OUT
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          message: |
            Ran helmfile diff for app releases

            <details>
            <summary>Diff output</summary>
            ${{ steps.helm_diff.outputs.helmfile-stdout }}            
            </details>
          pr-number: ${{ steps.pr_number.outputs.result }}