name: Go Testing

on:
  pull_request:
    paths:
      - 'go-server/**'
defaults:
  run:
    working-directory: go-server

jobs:
  Test&Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ‘1.24.x’

      - name: Install dependencies
        run: go get ...

      - name: Run tests
        run: go test ./internal/... -v

      - name:
        run: go build -o go-server ./cmd/go-server/main.go

